on:
  workflow_dispatch:
  schedule:
    - cron: '0 16 * * *'

env:
  REGISTRY: ghcr.io

jobs:
  build-pulsar-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: apache/pulsar
          ref: master

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - run: java --version

      - name: Build Pulsar
        run: mvn clean install -B -ntp -DskipTests

      - name: Build Pulsar images
        run: mvn package -B -ntp -Pdocker,-main -DskipTests

      - name: List Docker images
        run: docker images

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push pulsar-test-latest-version image
        run: |
          BASH_IMAGE=apachepulsar/pulsar-test-latest-version:latest
          
          LATEST_IMAGE=ghcr.io/${{ github.actor }}/pulsar-test-latest-version:latest
          docker tag $BASH_IMAGE $LATEST_IMAGE
          docker push $LATEST_IMAGE

          PULSAR_VERSION=$(mvn -Dexec.executable='echo' -Dexec.args='${project.version}' --non-recursive exec:exec -q)
          PULSAR_SHA1=$(git rev-parse --short HEAD)
          SHA_IMAGE=ghcr.io/${{ github.actor }}/pulsar-test-latest-version:$VERSION-$PROJECT_SHA1
          
          docker tag $BASH_IMAGE $SHA_IMAGE
          docker push $SHA_IMAGE
