on:
  workflow_dispatch:
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build-pulsar-images:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          repository: apache/pulsar
          ref: master
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - run: java --version

      - name: Build Pulsar
        run: mvn clean install -B -ntp -DskipTests

      - name: Build Pulsar images
        run: mvn package -B -ntp -Pdocker,-main -DskipTests

      - name: List Docker images
        run: docker images
